### ISSUE TITLE
Suggest to set up CI for SAAF

### ISSUE THREAD

**Issue by yungyuc** [BlueBug12/SAAF#1]
I noticed that there is a [test file set up](https://github.com/BlueBug12/SAAF/blob/main/test.py), but there is not Github Action set up for the repository.  Having CI running should be help your productivity in development.

My 2 cents.

**Comment by BlueBug12** [comment]
Thanks for your advice! I'll do that after I complete my partial progress.

**Comment by yungyuc** [comment]
I am closing this issue since you have a plan.  You may open issues to track your own progress and tag me for discussions.
